import org.gradle.kotlin.dsl.resolver.prettyPrint

/*
 * This file was generated by the Gradle 'init' task.
 */

description = "client"
group = "io.brule"
version = "alpha"

val ktor_version: String by project

plugins {
    kotlin("js") version "1.7.10"
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(kotlin("test"))
    implementation("org.jetbrains.kotlin-wrappers:kotlin-react:18.0.0-pre.332-kotlin-1.6.21")
    implementation("org.jetbrains.kotlin-wrappers:kotlin-react-dom:18.0.0-pre.332-kotlin-1.6.21")
    implementation("org.jetbrains.kotlin-wrappers:kotlin-emotion:11.9.0-pre.332-kotlin-1.6.21")
    implementation("org.jetbrains.kotlin-wrappers:kotlin-react-router-dom:6.3.0-pre.332-kotlin-1.6.21")
    implementation("org.jetbrains.kotlin-wrappers:kotlin-redux:4.1.2-pre.332-kotlin-1.6.21")
    implementation("org.jetbrains.kotlin-wrappers:kotlin-react-redux:7.2.6-pre.332-kotlin-1.6.21")
    implementation("io.ktor:ktor-client-js:$ktor_version")
}

kotlin {
    js(IR) {
        binaries.executable()
        browser {
            buildDir = File("$projectDir/build")
            commonWebpackConfig {
                configDirectory = File("$projectDir/webpack.config.d")
                cssSupport.enabled = true
            }
            println("Build directory: ${buildDir.absolutePath}")
        }
    }
};