import org.gradle.internal.impldep.org.eclipse.jgit.lib.ObjectChecker.author
import org.jetbrains.kotlin.gradle.targets.js.webpack.*;
import java.util.Map.entry

/*
 * This file was generated by the Gradle 'init' task.
 */

description = "client"
group = "io.brule"
version = "alpha"

val ktor_version: String by project
val api_proxy_target: String by project
val client_port: String by project

plugins {
    kotlin("js") version "1.7.10"
    kotlin("plugin.serialization") version "1.7.10"
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(kotlin("test"))
    implementation("org.jetbrains.kotlin-wrappers:kotlin-react:18.0.0-pre.332-kotlin-1.6.21")
    implementation("org.jetbrains.kotlin-wrappers:kotlin-react-dom:18.0.0-pre.332-kotlin-1.6.21")
    implementation("org.jetbrains.kotlin-wrappers:kotlin-emotion:11.9.0-pre.332-kotlin-1.6.21")
    implementation("org.jetbrains.kotlin-wrappers:kotlin-react-router-dom:6.3.0-pre.332-kotlin-1.6.21")
    implementation("org.jetbrains.kotlin-wrappers:kotlin-redux:4.1.2-pre.332-kotlin-1.6.21")
    implementation("org.jetbrains.kotlin-wrappers:kotlin-react-redux:7.2.6-pre.332-kotlin-1.6.21")
    implementation("io.ktor:ktor-client-js:$ktor_version")
    implementation("io.ktor:ktor-client-content-negotiation:$ktor_version")
    implementation("io.ktor:ktor-serialization-kotlinx-json:$ktor_version")




    implementation(npm("react","18.2.0"))
    implementation(npm("react-dom","18.2.0"))
}

rootProject.buildDir = project(":client").buildDir


kotlin {

    js(IR) {

//        buildDir = project(":client").buildDir
        binaries.executable()

        compilations["main"].packageJson {
            version = "0.0.0"
            dependencies {
                "react" to "18.2.0"
                "react-dom" to "18.2.0"
            }
        }


        browser {
            commonWebpackConfig {

                val wpDir = "$buildDir/webpack"
                val distDir = "$buildDir/distributions"
                val wpReportsDir = "$wpDir/reports"
                val srcResourcesDir = "$projectDir/src/main/resources"

                mkdir(wpDir)
                mkdir(distDir)
                mkdir(wpReportsDir)

                mode = KotlinWebpackConfig.Mode.DEVELOPMENT

                outputPath = File(distDir)

                configDirectory = File("$projectDir/webpack.config.d")
                bundleAnalyzerReportDir = File(wpReportsDir)
                reportEvaluatedConfigFile = File(wpReportsDir, "webpack.config.js")
                devServer = KotlinWebpackConfig.DevServer(
                    port = client_port.toInt(),
                    proxy = mutableMapOf(
                        "/api" to api_proxy_target
                    ),
                    static = mutableListOf(
                        srcResourcesDir
                    )


                )
                cssSupport.enabled = true
                devtool = WebpackDevtool.EVAL_SOURCE_MAP
                showProgress = true
                sourceMaps = true
                export = true
                progressReporter = true

                distribution {
                    directory = File(distDir)
                }
            }
        }
    }
}

rootProject.plugins.withType<org.jetbrains.kotlin.gradle.targets.js.yarn.YarnPlugin> {
    rootProject.the<org.jetbrains.kotlin.gradle.targets.js.yarn.YarnRootExtension>()
        .apply {
            lockFileDirectory = project(":client").projectDir
            lockFileName = "yarn.lock"
            ignoreScripts = false
        }
}