volumes:
  client_gradle:
    driver: local
  client_build:
    driver: local

services:
  gateway:
    container_name: gateway
    image: registry.access.redhat.com/ubi8/nginx-120
    command: nginx -g "daemon off;"
    ports:
      - 80:8080
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:z
      - ./gateway/modules/:/etc/nginx/modules/:z
    environment:
      - NGINX_HOST=playground.brule.io
      - NGINX_PORT=8080
    depends_on:
      - auth
      - client
      - server

  client:
    container_name: client
    image: brule.io/playground/client:latest
    working_dir: /app
    build:
      context: ../../client
      dockerfile: src/main/docker/Dockerfile.dev
    command: client.entrypoint.sh
    ports:
      - 9000:8080
    environment:
      - NODE_ENV=development
      - PORT=8080
    volumes:
      - ../../:/app:z
      - ../../client/client.entrypoint.sh:/usr/local/bin/client.entrypoint.sh:z
      - ~/.m2:/home/app/.m2:z
      - client_gradle:/app/.gradle:rw
      - client_build:/app/client/build:rw

  server:
    container_name: server
    image: brule.io/playground/server:latest
    privileged: true
    working_dir: /app
    entrypoint: server.entrypoint.sh
    build:
      context: ../../server
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - 9001:8080
    environment:
      - PORT=8080
      - QUARKUS_LAUNCH_DEVMODE=true
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ../../:/app:z
      - ../../server/server.entrypoint.sh:/usr/local/bin/server.entrypoint.sh:z
      - ~/.m2:/home/app/.m2:z
    tmpfs:
      - /app/.gradle
      - /app/server/build

  auth:
    container_name: auth
    image: quay.io/keycloak/keycloak-x
    command: start-dev
    volumes:
      - ./auth/keycloak.properties:/opt/keycloak/conf/keycloak.properties:z
      - ./auth/development-realm.json:/opt/keycloak/conf/development-realm.json:z
    ports:
      - 9002:8080
    environment:
      - KEYCLOAK_IMPORT=/opt/keycloak/conf/development-realm.json -Dkeycloak.profile.feature.upload_scripts=enabled
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
