volumes:
  web_build_root:
    driver: local
  web_build_src:
    driver: local
  web_build:
    driver: local
  web_build_gradle:
    driver: local

services:
  gateway:
    container_name: gateway
    image: registry.access.redhat.com/ubi8/nginx-120
    command: nginx -g "daemon off;"
    ports:
      - 80:8080
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:z
      - ./gateway/modules/:/etc/nginx/modules/:z
    environment:
      - NGINX_HOST=playground.brule.io
      - NGINX_PORT=8080
    depends_on:
      - auth
      - web
      - server

  web:
    container_name: web
    image: brule.io/playground/web:latest
    working_dir: /app
    build:
      context: ../../web
      dockerfile: src/main/docker/Dockerfile.dev
    command: web.entrypoint.sh
    ports:
      - 9000:8080
    environment:
      - NODE_ENV=development
      - PORT=8080
    volumes:
      # mount the whole source tree to the container
      - ../../:/app:z
      # mask the build directories
      - web_build_root:/app/build:rw
      - web_build_src:/app/buildSrc/build:rw
      - web_build:/app/web/build:rw
      # put the entrypoint in the path
      - ../../web/web.entrypoint.sh:/usr/local/bin/web.entrypoint.sh:z
      # load local m2 repo so it can use cached dependencies
      - ~/.m2:/home/app/.m2:z
      - web_build_gradle:/app/.gradle


  server:
    container_name: server
    image: brule.io/playground/server:latest
    privileged: true
    working_dir: /app
    entrypoint: server.entrypoint.sh
    build:
      context: ../../server
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - 9001:8080
    environment:
      - PORT=8080
      - QUARKUS_LAUNCH_DEVMODE=true
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ../../:/app:z
      - ../../server/server.entrypoint.sh:/usr/local/bin/server.entrypoint.sh:z
      - ~/.m2:/home/app/.m2:z
    tmpfs:
      - /app/.gradle
      - /app/server/build

  auth:
    container_name: auth
    image: quay.io/keycloak/keycloak-x
    command: start-dev
    volumes:
      - ./auth/keycloak.properties:/opt/keycloak/conf/keycloak.properties:z
      - ./auth/development-realm.json:/opt/keycloak/conf/development-realm.json:z
    ports:
      - 9002:8080
    environment:
      - KEYCLOAK_IMPORT=/opt/keycloak/conf/development-realm.json -Dkeycloak.profile.feature.upload_scripts=enabled
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
