# Dockerfile.dev : client

# This image is meant to have the source volume mounted into it
# at /app
FROM fedora:36

RUN echo "Updating packages" && dnf update -y; dnf install unzip zip curl wget -y; dnf clean all -y;

# Make a user to run the app as
RUN useradd -ms /bin/bash -d /home/app app
USER app

RUN echo "Installing packages" &&  curl -s "https://get.sdkman.io" | bash

RUN echo "Installing Java" && \
    source  ~/.sdkman/bin/sdkman-init.sh &&\
    sdk install java 21.3.0.r17-grl


WORKDIR /app
EXPOSE 9000
ENV PORT 9000